version: '2'
services:
  discourse:
    image: community-discourse:v1
    network_mode: "host"
    command: >
      sh -c "
        set -x;
        whoami;
        su discourse;
        whoami;
        cd /var/www/discourse;
        RAILS_ENV=production bundle exec script/discourse remap '/uploads' '/community/uploads'
        cp -r public/* public-nginx/
        LD_PRELOAD=$RUBY_ALLOCATOR HOME=/home/discourse USER=discourse bundle exec config/unicorn_launcher -E production -c config/unicorn.conf.rb
      "
    environment:
      - RAILS_ENV=production
      - UNICORN_WORKERS=3
      - UNICORN_SIDEKIQS=1
      - DISCOURSE_HOST=localhost
      - DISCOURSE_HOSTNAME=localhost
      # - DISCOURSE_CDN_URL=http://localhost/community
      - DISCOURSE_RELATIVE_URL_ROOT=/community
      - DISCOURSE_DB_HOST=127.0.0.1
      - DISCOURSE_DB_NAME=discourse
      - DISCOURSE_DB_PASSWORD=tmp
      - DISCOURSE_DB_PORT=5439
      - DISCOURSE_DB_USERNAME=tmp
      - DISCOURSE_DATABASE_USER=tmp
      - DISCOURSE_REDIS_HOST=127.0.0.1
      - DISCOURSE_REDIS_PORT_NUMBER=6379
    volumes:
        - ./public:/var/www/discourse/public-nginx
